### ISSUE TITLE
Add a source control system configuration and templating engine to the unity auto builder app

### ISSUE THREAD

**Issue by Kavignon** [Kavignon/Functional_Experimentations#2]
### Feature Request

This issue tracks the implementation of support for multiple source control systems in the Unity AutoBuilder System. Currently, we only support Git, but we want to expand our capabilities to accommodate other source control systems in the future.

### To-Dos

- [ ] Add support for other source control systems.
- [ ] Add support for generic source control system configuration.
- [ ] Add support for generic source control system commands.
- [ ] Add support for generic source control system commit message template.
- [ ] Support the generic source control system's commit message template variables.

### Future Plans

We envision moving towards an open configuration system that allows users to use any source control system. This will involve:

- [ ] Creating configuration files for each source control system.
- [ ] Dynamically loading configuration files based on the selected source control system.
- [ ] Specifying supported commands for each source control system.
- [ ] Allowing customization of commit message templates.
- [ ] Defining commit message template variables.

Here's an example structure for a configuration file:

```json
{
    "sourceControlSystem": "Git",
    "sourceControlSystemConfiguration": {
        "gitConfiguration": {
            "gitPath": "C:\\Program Files\\Git\\bin\\git.exe",
            "gitRepositoryPath": "C:\\Users\\user\\Documents\\GitHub\\UnityAutoBuilder,"
            "gitBranch": "master",
            "git commit message": "Build from UnityAutoBuilder."
        },
        "gitCommands": {
            "gitStatus": "git status",
            "gitAdd": "git add,"
            "gitCommit": "git commit",
            "gitPush": "git push",
            "gitTag": "git tag",
            "gitPushTag": "git push --tags"
        },
        "gitCommitMessageTemplate": "Build from UnityAutoBuilder - {0} - {1} - {2}",
        "gitCommitMessageTemplateVariables": [
            "BuildNumber",
            "BuildTarget",
            "BuildPlatform"
        ]
    }
}
